### ISSUE TITLE
Twig: improve doc page styles

### ISSUE THREAD

**Issue by justintemps** [international-labour-organization/designsystem#1080]
Right now, the Doc page is using a combination of default Storybook styles and topography settings from the DS. The design is a mismash of type and spacing that doesn't look very nice. 

<img width="1290" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/79d11b56-5448-4717-a7ba-d69f62966434">

Instead, we should be applying the same styles here that we use for the [RichText component ](https://twig.ui.ilo.org/?path=/docs/components-content-rich-text--rich-text)

We should also come up with nicer code formatting.

**Comment by justintemps** [comment]
We also need to remove other SCSS variables from `_typography` and `_typographymonorepo` 

```scss
html,
body {
  color: $color-font-base; // <--- this
  font-family: var(--ilo-fonts-copy);
  font-size: #{$type-base-size}; // <--- this
  line-height: #{$type-base-line-height};
  letter-spacing: $type-base-letter-spacing; // <--- this
  -webkit-font-smoothing: antialiased;
}
```
