### ISSUE TITLE
Improvement to the tabs components

### ISSUE THREAD

**Issue by ademarco** [international-labour-organization/designsystem#1244]
The following improvements [where proposed](https://github.com/international-labour-organization/ilo_base_theme/pull/43/files#diff-efe22ee6c2180f56d81b7b8ad983815e9b164d8b0b118d0826b5a90dbd28d107R12) in the ILO Base Theme. The scope of this ticket is to consider them for inclusion in the DS, so not to have discrepancies between the theme and the DS.

```scss
  // UX improvement 1
  // Avoid label "jumping" when hovering an inactive tab.
  .ilo--tabs.tabs--js .ilo--tabs--selection--button[aria-selected="false"]:not(:hover) {
    border-top: px-to-rem(3px) solid transparent;
  }

  // UX improvement 2
  // When a tab is active it should not be clickable, because its content is already visible.
  // For the same reason it should not show hovering effects.
  .ilo--tabs.tabs--js .ilo--tabs--selection--button[aria-selected="true"] {
    pointer-events: none;
  }

  // Secondary tabs
  .ilo--tabs--secondary {
    display: flex;
    flex-wrap: wrap;
    margin-block: 2rem;
    gap: 10px;

    .ilo--tabs--selection--button {
      display: block;
      padding: 0.2em 1em;
      font-size: 16px;
      font-weight: 600;
      color: #230050;
      text-decoration: none;

      &[aria-selected="false"] {
        border-bottom: 2px solid transparent;
        background-color: var(--ilo-color-background-highlight);

        &:hover {
          color: var(--ilo-color-blue);
          border-bottom-color: var(--ilo-color-blue);
          background-color: var(--ilo-color-background-hover);
        }
      }

      &[aria-selected="true"] {
        color: var(--ilo-color-blue-dark);
        border-bottom: 2px solid var(--ilo-color-blue-dark);
        pointer-events: none;
      }
    }
  }
```
