### ISSUE TITLE
ILO Design System Theme Proposal

### ISSUE THREAD

**Issue by GGKapanadze** [international-labour-organization/designsystem#999]
# Context

The proposal idea comes after discussing the #896. 

First of all, let's define how the current implementation works. The mono-repo has a package named `@ilo-org/theme`, with a simple idea to define an abstract variable system that will be a source of truth for the `@ilo-org/styles` package. It uses JSON files to define the configuration, something like this: 

```json
  "spacing": {
    "base": { "value": "8px" },
    "root": { "value": "4px" } 
 }
```
After the definition, there is a  [built](https://github.com/international-labour-organization/designsystem/blob/develop/packages/themes/build.js) step involved(it uses `-` for the variable concatenation. ) that will produce the `SCSS` variables from the configuration that are directly accessible

```scss
{
  .example {
    margin-top: $spacing-base; 
  }
}
```

## Problem
Now, let's look at a more complex, real-life use case. For example, look at the `Hero` component and imagine we want to tweak its style. We will start from the `_hero.scss` file and we will notice the `$spacing-hero-card-corner-cut-height-lg` variable. If we want to modify the actual value. First, we will try to do the `go to definition` aka (`cmd` + click). We will end up inside the `_tokens.scss` file, which is a built file and **should not be modified**. Next, we'll try to use the global search, but none of them appears to be a JSON file 

![image](https://github.com/international-labour-organization/designsystem/assets/36326203/e02532fd-6f6f-4bec-a092-5b676cb31292)

To really modify the value, we should look at the variable structure, and we'll end up inside `spacing/hero.json`, and here it is 

```json
{
  "spacing": {
    "hero-card": {
      "corner-cut": {
        "width": {
          "sm": { "value": "72px" },
          "lg": { "value": "116px" }
        },
        "height": {
          "sm": { "value": "40px" },
          "lg": { "value": "64px" }
        }
      }
    }
  }
}
```

Despite a bad developer experience, this approach also introduced the dead code elimination problem. There is no easy way to detect unused tokens and purge them. This may evolve into a bigger maintenance problem that will take a lot of work to debug. You may also notice the second issue, as mentioned above: the `-` is used for variable concatenation for JSON nested values, but the `-` is also utilized for word separation. So unexpected collisions may happen:

```json
{
  "spacing": {
    "herox": {
      "card": {
        "padding": {
          "value": "11px"
        }
      }
    },
    "herox-card": {
      "padding": {
        "value": "18px"
      }
    }
  }
}
```
An example like this will give you the compiler warning, but it will still generate the following `SCSS`, and this issue isn't scoped to only one file 
```SCSS
$spacing-herox-card-padding: 11px !default;
$spacing-herox-card-padding: 18px !default;
```

Another scenario where improvements can be made is variable referencing. For example, we want to use the `base` spacing value for the heading margin definition. If we want to reference another variable, we should be dependent on its string representation without any IntelliSense, but instead of `-` we should `.` for file reference

```json
{
   "heading": {
      "margin": {
         "value": "{spacing.base}"
       }
   }
}
```

There is also an implementation problem. Despite having a bad referencing system, the system isn't utilizing it fully. Some JSON files still use direct values. Here is an example from `_boxpadding.json` 

```json
 "credit": {
    "small": {
      "bottom": { "value": "4px" },
      "left": { "value": "12px" },
      "right": { "value": "8px" },
      "top": { "value": "4px" }
    },
    "medium": {
      "bottom": { "value": "4px" },
      "left": { "value": "12px" },
      "right": { "value": "8px" },
      "top": { "value": "4px" }
    },
    "large": {
      "bottom": { "value": "4px" },
      "left": { "value": "12px" },
      "right": { "value": "8px" },
      "top": { "value": "4px" }
    }
  }
```

To sum up, it will be better to start the migration to the new system for future development, especially for tasks like #970 and #896. 

# CSS Variables
 
This proposal keeps the idea of future theming capabilities. It aims to improve the developer experience, maintenance, composability, and theme extension, but it also tries to introduce a framework for how the theme should integrate into styles. The new theme implementation will leverage CSS variables. It has about [97% browser support](https://caniuse.com/?search=css%20variables), it doesn't require any extra build steps, and all modern editors have the necessary tooling. 

The new theming system will live inside the `@ilo-org/styles` package. It will have two high-order scopes 
- Foundation 
- Component

![image](https://github.com/international-labour-organization/designsystem/assets/36326203/309d1c4b-7768-45aa-b828-47e7af66a3d8)

## Foundation Scope
The foundation scope will be a core part of the theme. It will define the main building blocks like: 

- Typography: everything related to text rendering
- Colors: general colors for the design system, like: `$brand-ilo-blue`
- Spacing: general spacing value that will be used for both margin and padding
- Sizing: view-port definitions, border radiuses, etc. 

These blocks will completely cover the shared configuration for all components.  The file structure will look something like this
```sh
.
└── styles/
    └── scss/
        ├── theme/
        │   ├── _foundation.scss 
        │   └── index.scss
        └── components/
            └── ...
```

![image](https://github.com/international-labour-organization/designsystem/assets/36326203/0a860c67-eba2-4fab-9372-f80d14642524)

If `_foundation.scss` becomes too big, we can split them into separate modules. Here is a brief version for **Theme Foundation** 

```scss
:root {
  /**
    * Typography
    */
  --ilo-scale: 1; // default scale for the design system
  --ilo-font-family: Overpass, Noto Sans, Noto Sans CJK JP, Yu Gothic,
    Hiragino Sans, TakaoPGothic, PingFang SC, Microsoft YaHei, 微软雅黑,
    sans-serif; // equivalent to $fonts-display
  --ilo-font-family-headings: var(
    --ilo-font-family
  ); // separate variable for headings
  --ilo-font-family-monospace: monospace; // monospace font
  --ilo-line-height: 146%; // based on mostly used body line height inside figma design typography settings

  // ... more typography vars

  /**
    * Colors
    */
  --ilo-color-blue: rgba(30, 45, 190, 1);
  --ilo-color-blue-lighter: rgba(235, 245, 253, 1);
  --ilo-color-blue-light: rgba(190, 220, 250, 1);
  --ilo-color-blue-dark: rgba(35, 0, 80, 1);
  --ilo-color-blue-medium: rgba(30, 45, 190, 20%);

  // ... more color vars

  /**
    * Sizing
    */
  --ilo-breakpoint-xs: 320px;
  --ilo-breakpoint-sm: 414px;
  --ilo-breakpoint-md: 610px;
  --ilo-breakpoint-lg: 1024px;
  --ilo-breakpoint-xl: 1168px;
  --ilo-breakpoint-xxl: 1440px;
  --ilo-border-radius: calc(
    px-to-rem(2) * var(--ilo-scale)
  ); // every value that is not meant to be scalable should use --ilo-scale

  // ... more sizing vars

  /**
    * Spacing
    */
  --ilo-spacing-base: calc(
    px-to-rem(4) * var(--ilo-scale)
  ); // non typography, values are always referenced from the scale system
}
```

Let's start with the rules first 
- All variables provided by the ilo theme, both foundation and component scope, should use the `ilo-` prefix 
- Every value meant to be scalable should use `--ilo-scale` variable. 
- Variable should be structured in a specific way 
![image](https://github.com/international-labour-organization/designsystem/assets/36326203/02fce147-db44-4294-9323-b05f7cf45180)
   - name and size can be used together, if needed `name->size`.
- Foundation file, **should not** include any component specific styling
- Foundation variables can reference each other 

## Component scope

The main question remains: Where are the component variables?  Component variables should not be defined separately. Each component should declare its own set of variables at the top of the file that will be used across component styling only. 

### Rules

1) Variables structure

![image](https://github.com/international-labour-organization/designsystem/assets/36326203/25da2a00-6ca7-4ed1-938c-0e663cac40d1)
- component variables are more flexible. They may include sublayers. For example, if we want to define the width and height of video component's control bar we can use 
```scss
--ilo-video-control-bar-width: 12px;
```
- if the component has breakpoint separations, the variables should be separated

```scss
--ilo-multilink-card-md-padding: 12px;
--ilo-multilink-card-lg-padding: 16px;
--ilo-multilink-card-xl-padding: 20px;
```

2) What should be extracted as a variable? 

This component scope aims to define certain variables only within its scope. It will allow an end user to override properties for only the current component. To achieve this, the component will reference some of the foundation variables, giving us the power to have the correct scoping for each component. Here are the mandatory variable properties
- background-color
- color
- border-radius
- padding: padding (container only), padding-block, padding-inline
- width: `width` (container level), max-width, min-width
- height: `height` (container level), max-height, min-height

For example, background-color of the promo card can be the main blue color, but it should be declared separately and reference the foundation

```scss
--ilo-card-promo-backgroun-color: var(--ilo-color-blue); 
```

After mandatory variables, the component can expose any other variable on any sublayer of the component. For example, we can define separate font-size for multilink card title like
```scss

.ilo--card {
  $self: &;

  &__type {
    &__multilink {
       --ilo-card-multilink-title-font-size: 12px;
    }
  }
}
```

- Besides mandatory properties, the component can directly access the foundation variable on the target property. 
- The developer can expose any other variable related to the component that can be discussed during PR. 

- Layout, positioning, static background images, or nested with and heights aren't required to be declared as a variable 
- Hover and focus variables aren't necessary (this could be discussed)
- % and view-port sizing-based values can also be omitted 

3) If components share the same root class, for example Card component, the definitions should be made at the component-specific wrapper 

```scss
// promo card
.ilo--card {
  $self: &;

  &--wrapper__type__promo {
    --ilo-card-promo-width: 123px;
 }
}
```

4) Mixins

- Mixins that use the old token system should move to foundation values: `spacing` , `px-to-rem`, `breakpoints`
-  `map-get`, `font-family`, `font-wight`,  should be removed and moved to the foundation/component level
-  `spacingvalues`, `bordevalues`, `boxpadding` should be removed and abstracted at the component level
-   component specific mixins like `videobutton` should move to the component level and use CSS variables 

Let's walk by the example if we want to refactor the `accordion` component

- define all mandatory variables 

```scss
.#{$prefix}--accordion {
  --ilo-accordion-transition-timing:  500ms;
  --ilo-accordion-max-height: 300px;
  --ilo-accordion-button-color: var(--ilo-color-blue);
  --ilo-accordion-button-padding-md-inline: calc(var(--ilo-spacing-base) * 3);
  --ilo-accordion-button-padding-md-block: calc(var(--ilo-spacing-base) * 2);
  --ilo-accordion-button-padding-lg-inline: calc(var(--ilo-spacing-base) * 4);
  --ilo-accordion-button-padding-lg-block: calc(var(--ilo-spacing-base) * 5);
  --ilo-accordion-button-border: 2px solid var(--ilo-color-lighter-blue);

  $breadcrumb: &;
}
```
- Then, we can use them directly for target properties

```scss
 &--button {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    width: 100%;
    margin: 0;
    padding-block: var( --ilo-accordion-button-padding-md-block);
    padding-inline-end: var( --ilo-accordion-button-padding-md-inline);
    transition: all var(--ilo-accordion-transition-timing) ease-in-out;
    background-color: var( --ilo-accordion-button-color)t
    background-position: calc(100% - px-to-rem(6px)) center;
    background-repeat: no-repeat;
    background-size: px-to-rem(24px) px-to-rem(24px);
    border-top: var(--ilo-accordion-button-border);
    // ..rest

    &__large {
      @include font-styles("headline-6");
      padding-block: var( --ilo-accordion-button-padding-lg-block);
      padding-inline-end: var( --ilo-accordion-button-padding-lg-inline);
    }
}
```
- We can also reference foundation variables 

```scss
&__open {
      max-height: 100vh;
      transition: all var(--ilo-accordion-transition-timing) ease-in-out;

      &#{$panel}__scroll {
        padding-right: calc(var(--ilo-spacing-base) * 4);
      }
    }
```

- And then we can refactor old mixins
> font-style example

```scss
&--label {
      white-space: nowrap;
      overflow-x: clip;
      text-overflow: ellipsis;
      max-width: 30ch;
      font-family: var(--ilo-font-family-body-xxs);
      font-weight: 400;
    }
```

**Comment by justintemps** [comment]
Hey @GGKapanadze this looks really exciting, I agree wholeheartedly with the approach. Just a few things:

## We'll need to document a list of the customisable variables for each component in Storybook. What's the best way to do that?

## Prefixes

The rest of the DS uses a variable `$prefix` to namespace classnames so that it's clear what comes from the DS and what doesn't. This should also eventually make it clear if you've applied custom theming to the DS or not.

If that's the case, then we should do one of two things:

### Use prefixes in the CSS vars as well

This won't be nice or be fun to work with, but it will solve the problem for users. This is my preferred solution.

```scss
--#{$prefix}-accordion-transition-timing:  500ms;

&__open {
      max-height: 100vh;
      transition: all var(--#{$prefix}-accordion-transition-timing) ease-in-out;

      &#{$panel}__scroll {
        padding-right: calc(var(--#{$prefix}-spacing-base) * 4);
      }
    }
```

### Use some other neutral prefix

We could use `theme` or `ds` or `ds-theme` that will look nicer in source code, but could still lead to some confusion.

## Color theming

To make the DS as themeable as possible, it seems like we should use semantic names like `primary`, `accent`, `background` etc. This will also make it easier to implement light and dark themes and allow people to apply a totally different brand just by changing these few variables.

## Animations

We should also expose standard values for animation timings as you'll often have multiple transitions running together and they need to be synced. Something like 

```scss
--ilo-transition-fast: 250ms;
--ilo-transition-slow: 500ms;
--ilo-transition-slower: 1000ms;
```

## Naming convention

I think the naming convention is great, but above you have this example:

```scss
-ilo-multilink-card-md-padding: 12px;
```

and it seems like it should be this instead:

```scss
--ilo-multilink-card-padding-md: 12px;
```
